name: absence
channels:
  - default
  - conda-forge
dependencies:
 - python #=3.9.7
 - ipykernel #=5.3.4
 - numpy #=1.20.1
 - pandas #=1.2.4
 - pyodbc #=4.0.30
 - sqlalchemy #=1.4.7
 - pathlib2 #=2.3.6
 - toml #=0.10.2
 - nbformat #=5.1.3
 - pip #=21.0.1
 - openpyxl #=3.0.9
 - pip:
    - -e .
